// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d6f7ca38-09ff-4024-9b9f-6e7135ea0c29",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ctuuhZ3me",
    "aws_user_pools_web_client_id": "5dlk7ok4t0gvqcdeq6rr3lhg5d"
};


export default awsmobile;
